### ISSUE TITLE
HRSCD 数据集链接已失效

### ISSUE THREAD

**Issue by 1pengliu** [long123524/HGINet-torch#3]

**Comment by long123524** [comment]
> _No description provided._
您好，我试了一下，可以正常进入

**Comment by 1pengliu** [comment]
> > _No description provided._
> > 您好，我试了一下，可以正常进入
<img width="511" alt="image" src="https://github.com/user-attachments/assets/50883068-ffe3-44d5-8208-8fcc7b3955e1">
请问这这个链接里是包含了福州和厦门这两个SCD数据集吗？

**Comment by long123524** [comment]
> > > _No description provided._
> > > 您好，我试了一下，可以正常进入
> 
> <img alt="image" width="511" src="https://private-user-images.githubusercontent.com/154670486/361145194-50883068-ffe3-44d5-8208-8fcc7b3955e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ1MDg4MDcsIm5iZiI6MTcyNDUwODUwNywicGF0aCI6Ii8xNTQ2NzA0ODYvMzYxMTQ1MTk0LTUwODgzMDY4LWZmZTMtNDRkNS04MjA4LThmY2M3YjM5NTVlMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyNFQxNDA4MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDNmZjJhYTc5Zjg5ODdmYTYxN2ExYjg2YTRkNzYwYTZhZTE1ODFiODQ1ZWU2MDIyNTVmYTMwZjRlMjdhY2E2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0uN7uNV6gKFq1ntvW8e3IOSoZqmmczyVuuxCGKsnHOg"> 请问这这个链接里是包含了福州和厦门这两个SCD数据集吗？

提供的福州数据集
