### ISSUE TITLE
能否提供一下您处理好后的HRSCD数据集呢

### ISSUE THREAD

**Issue by Dap1Aa** [long123524/HGINet-torch#4]

**Comment by long123524** [comment]
> _No description provided._

通过网盘分享的文件：HRSCD.zip
链接: https://pan.baidu.com/s/1uhGw_rRE8XnvcPT02h3Cmw 提取码: duk5 
--来自百度网盘超级会员v5的分享

**Comment by Dap1Aa** [comment]
> > _No description provided._
> 
> 通过网盘分享的文件：HRSCD.zip 链接: https://pan.baidu.com/s/1uhGw_rRE8XnvcPT02h3Cmw 提取码: duk5 --来自百度网盘超级会员v5的分享

非常感谢您的恢复！祝您生活愉快，事事顺心！
